config/routes.rb
Rails.application.routes.draw do
  root :to => 'reserves#new'
  post "/reserves/confirm" => "reserves#confirm"
  post "/reserves/create" => "reserves#create"
  patch "/reserves/create" => "reserves#create"
  resources :reserve do
  end

end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  attr_accessor :email_confirmation
  validates :name, presence: true, length: { maximum: 256 }
  validates :kana, length: { maximum: 256 }
  validates :email, presence: true, confirmation: true, email_format: true
  validates :email_confirmation, presence: true
  validates :number, presence: true, numericality: true, inclusion: { in: 1..10 }
  validates :note, length: { maximum: 1000 }
end

app/models/setting.rb
class Setting < ActiveRecord::Base
	scope :members, -> { where("name = 'members'").first }
	scope :totals, -> { where("name = 'totals'").first }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :basic_authenticate
  def basic_authenticate
    if Rails.env.development? || ENV['BASIC_AUTH'] == "ENABLED"
      authenticate_or_request_with_http_basic('Secret Area') do |urlname, password|
        [urlname, password] == ["kwww2","kannothx123"]
      end
    end
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  def new
      if check_stock
          @reserve = Reserve.new
        else
          render :soldout
        end
    end

    def create
      @reserve = Reserve.new(reserve_params)

      respond_to do |format|
        if @reserve.save
           MailSender.entry(@reserve).deliver #MailSender.entryに@reserveを渡す
           format.html { render action: 'complete' }
        else
           format.html { render action: 'new', notice: 'error'  }
        end
       end
    end

  def confirm
    @reserve = Reserve.new(reserve_params)
      respond_to do |format|
        if @reserve.valid?
           format.html
        else
           format.html { render action: 'new', notice: 'error'  }
        end
       end
  end

  def soldout
  end

  private
    def reserve_params
      params.require(:reserve).permit(:name, :kana, :email, :email_confirmation, :number, :note)
    end

    def check_stock
      # Settingsテーブルから事前予約可能チケットの残分を取得
      @settings = Setting.new
      @reserve = Reserve.new
      stock = Setting.totals.try(:value).to_i - Setting.members.try(:value).to_i
      # 売れたチケットの枚数を取得
      sold = Reserve.sum(:number).to_i
      if stock > sold
        return true
      else
        return false
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thanks!Kオーケストラ第２回演奏会 チケット事前予約</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta http-equiv="content-type" content="text/html ;charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53478111-2', 'auto');
  ga('send', 'pageview');

</script>
<div class="container">
<img src="http://www.thanks-k.com/img/header.gif" id="logo" alt="菅野よう子楽曲演奏団体 Thanks!K" />
<h1>Thanks!Kオーケストラ第２回演奏会</h1>
<h2>チケット事前予約</h2>
<%= yield %>
</div>
</body>
</html>

app/views/mail_sender/entry.text.erb
<%= @reserve.name %>様

ご予約いただきありがとうございます。
以下の内容で予約いたしました。

===========

発券番号　　　： <%= @reserve.id %>
お名前（漢字）： <%= @reserve.name %>
お名前（かな）： <%= @reserve.kana %>
メールアドレス： <%= @reserve.email %>
予約枚数　　　： <%= @reserve.number %> 枚
料金　　　　　： 500円 x <%= @reserve.number %> 枚 = <% price = @reserve.number * 500 %><%= price %> 円
備考　　　　　： <%= @reserve.note %>

===========

このメールは送信専用です。
チケットのキャンセルなどお問い合わせは
thanksk.orch.ticket@gmail.com までお願いします。

演奏会場でお待ちしています。
Thanks!Kオーケストラ一同 

app/views/reserves/complete.html.erb
<h2>事前予約が完了しました。</h2>

<p>
ありがとうございます。<br>
ご入力いただいたメールアドレスに、ご予約内容を送信いたしました。<br>
</p>

<div class="well">
	<h3>発券番号：<%= @reserve.id %></h3>
	<p>
	演奏会当日、受付にて発券番号と一緒に料金をお支払ください。<br>
	予約枚数のチケットをお渡しいたします。
	</p>
</div>

app/views/reserves/confirm.html.erb
<h2>予約内容をご確認ください</h2>

<p>以下の内容で事前予約します。</p>



<%= simple_form_for @reserve,:url => reserves_create_path, :html => {:class => 'form-horizontal'} do |f| %>

  <%= f.hidden_field :name %>
  <%= f.hidden_field :kana %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :email_confirmation %>
  <%= f.hidden_field :number %>
  <%= f.hidden_field :note %>
  <div class="control-group">
    お名前（漢字）： <%= @reserve.name %><br>
    お名前（かな）： <%= @reserve.kana %><br>
    メールアドレス： <%= @reserve.email %><br>
    予約枚数　　　： <%= @reserve.number %> 枚<br>
    備考　　　　　： <%= @reserve.note %>
  </div>

<p class="well">
入力いただいたアドレスに予約完了メールを送付いたしますので、受信拒否等の設定をされている場合は、 ticket@thanks-k.com からのメールを受信できるように設定してください。
</p>

   <div class="form-actions">
       <input class="btn form-control" value="修正する" onclick="history.back()" type="button" />
       <%= submit_tag('予約する', class: "btn form-control btn-primary", :disable_with => "送信中..." ) %>
  </div>
<% end %>

app/views/reserves/new.html.erb
<p>
チケット：事前予約価格 1枚500円（予約なしの場合は1000円）
</p>

<div id="step-for-reserve" class="well">
<h3>予約手順</h3>
<ol>
  <li>以下のフォームから必要事項を入力ください。</li>
  <li>予約頂きますと発券番号が表示されますので保存ください（メールでも通知致します）。</li>
  <li>演奏会当日、受付にて発券番号と一緒に料金をお支払ください。</li>
  <li>予約枚数のチケットをお渡しいたします。</li>
</ol>
</div>

<%= simple_form_for @reserve, :url => {:action => 'confirm'}, :html => {:class => 'form-horizontal'} do |f| %>

<% if @reserve.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <ul>
      <% @reserve.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>


  <div class="control-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
    <div class="control-group">
    <%= f.label :kana %>
    <%= f.text_field :kana, :class => "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :email_confirmation %>
    <%= f.text_field :email_confirmation, :class => "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :number %>
    <%= select :reserve, :number,[1,2,3,4,5,6,7,8,9,10] %>枚
  </div>
  <div class="control-group">
    <%= f.label :note %>
    <%= f.text_area :note, :size => "40x3" %>
  </div>

   <div class="form-actions">
       <%= f.submit class: "btn form-control btn-primary", :value => '予約内容を確認する' %>
  </div>
<% end %>

app/views/reserves/soldout.html.erb
    <div class="alert">
      <h2>満員御礼！</h2>
      <p>
      たくさんのご予約、ありがとうございました。<br>
      事前予約は定員に達したため、締め切らせていただきました。
      </p>
    </div>